use msftcangoblowm/drain-swamp-action
- ci: use msftcangoblowm/drain-swamp-action
- chore(workflows): review gha versions

diff --git a/.github/workflows/testsuite.yml b/.github/workflows/testsuite.yml
--- a/.github/workflows/testsuite.yml
+++ b/.github/workflows/testsuite.yml
@@ -65,54 +65,70 @@ jobs:
       fail-fast: false
 
     steps:
-      - name: "Check out the repo"
-        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+    - id: prepare-config-settings
+      name: >-
+        Build Plugin parameters
+      uses: 'msftcangoblowm/drain-swamp-action@v1'
+      env:
+        SET_LOCK: ${{ vars.DRAINSWAMP_SET_LOCK }}
+      with:
+        plugin_parameters: '{"set-lock": "${{ env.SET_LOCK }}", "kind": "current"}'
+        checkout: true
+        fetch_tags: true
+        python_version: "${{ matrix.python-version }}"
 
-      - name: "Set up Python"
-        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
-        with:
-          python-version: "${{ matrix.python-version }}"
-          allow-prereleases: true
-          # At a certain point, installing dependencies failed on pypy 3.9 and
-          # 3.10 on Windows.  Commenting out the cache here fixed it.  Someday
-          # try using the cache again.
-          cache: pip
-          cache-dependency-path: |
-            requirements/*${{ env.LOCK_SUFFIX }}
+    - name: "Download artifact"
+      uses: actions/download-artifact@v4
+      with:
+        name: config-settings-${{ matrix.os }}-${{ matrix.python-version }}
+        path: '${{ runner.temp }}'
 
-      - name: "Show environment"
-        run: |
-          set -xe
-          python -VV
-          python -m site
-          # For extreme debugging:
-          # python -c "import urllib.request as r; exec(r.urlopen('https://bit.ly/pydoctor').read())"
-          env
+    - name: "Check out the repo"
+      uses: actions/checkout@6d193bf28034eafb982f37bd894289fe649468fc # v4.1.7
 
-      - name: "Install dependencies"
-        run: |
-          python -m pip install -r requirements/tox$LOCK_SUFFIX
-          python -m pip install -r requirements/prod$LOCK_SUFFIX
-          python -m pip install -r requirements/kit$LOCK_SUFFIX
+    - name: "Set up Python"
+      uses: actions/setup-python@v5.2.0
+      with:
+        python-version: "${{ matrix.python-version }}"
+        allow-prereleases: true
+        # At a certain point, installing dependencies failed on pypy 3.9 and
+        # 3.10 on Windows.  Commenting out the cache here fixed it.  Someday
+        # try using the cache again.
+        # cache: pip
+        # cache-dependency-path: |
+        #   requirements/*${{ env.LOCK_SUFFIX }}
 
-      # Create generated files: version file and .lnk files. sdist tarball ignored
-      - name: "Build sdist to run plugins. Create generated files"
-        env:
-          SET_LOCK: ${{ vars.DRAINSWAMP_SET_LOCK }}
-        run: |
-          set -xe
-          echo "python -m build -C--kind='current' -C--set-lock='$SET_LOCK'"
-          python -m build -C--kind="current" -C--set-lock="$SET_LOCK"
+    - name: "Show environment"
+      run: |
+        set -xe
+        python -VV
+        python -m site
+        # For extreme debugging:
+        # python -c "import urllib.request as r; exec(r.urlopen('https://bit.ly/pydoctor').read())"
+        env
 
-      - name: "Run tox for ${{ matrix.python-version }}"
-        run: |
-          python -m tox -c tox-test.ini -- -rfsEX
+    - name: "Install dependencies"
+      run: |
+        python -m pip install -r requirements/tox$LOCK_SUFFIX
+        python -m pip install -r requirements/prod$LOCK_SUFFIX
+        python -m pip install -r requirements/kit$LOCK_SUFFIX
 
-      - name: "Retry tox for ${{ matrix.python-version }}"
-        if: failure()
-        run: |
-          # `exit 1` makes sure that the job remains red with flaky runs
-          python -m tox -- -rfsEX --lf -vvvvv && exit 1
+    # Create generated files: version file and .lnk files. sdist tarball ignored
+    - name: "Build sdist to run plugins. Create generated files"
+      run: |
+        # TOML file location ${{ runner.temp }}/${{ steps.outcome.inputs.toml_file_name }}
+        # env.DS_CONFIG_SETTINGS contains (OS independent) path to TOML file
+        python -m build
+
+    - name: "Run tox for ${{ matrix.python-version }}"
+      run: |
+        python -m tox -c tox-test.ini -- -rfsEX
+
+    - name: "Retry tox for ${{ matrix.python-version }}"
+      if: failure()
+      run: |
+        # `exit 1` makes sure that the job remains red with flaky runs
+        python -m tox -- -rfsEX --lf -vvvvv && exit 1
 
   # This job aggregates test results. It's the required check for branch protection.
   # https://github.com/marketplace/actions/alls-green#why
